---
deployment:
  tasks:
    - export DEPLOYPATH=$HOME/public_html
    - /bin/mkdir -p $DEPLOYPATH/css
    - /bin/mkdir -p $DEPLOYPATH/img
    - /bin/mkdir -p $DEPLOYPATH/storage/postsimg
    - /bin/cp -f public/index.cpanel.php $DEPLOYPATH/index.php
    - /bin/cp -f public/.htaccess $DEPLOYPATH/.htaccess
    - /bin/cp -f public/favicon.ico $DEPLOYPATH/favicon.ico
    - /bin/cp -f public/robots.txt $DEPLOYPATH/robots.txt
    - /bin/cp -rf public/css/. $DEPLOYPATH/css/
    - /bin/cp -rf public/img/. $DEPLOYPATH/img/
    - /bin/cp -f storage/app/public/postsimg/*.webp $DEPLOYPATH/storage/postsimg/
